// Mock user data
export const mockUsers = [
  {
    id: 1,
    firstName: 'Avery',
    lastName: 'Stone',
    email: 'avery.stone@northstar.health',
    phone: '(415) 610-1842',
    bio: 'Owns the patient intake web surfaces for a multi-region healthcare platform, with a focus on accessible form design, service recovery dashboards, and measurable conversion improvements.',
    location: 'San Francisco, CA',
    occupation: 'Clinical Experience Lead',
  },
  {
    id: 2,
    firstName: 'Priya',
    lastName: 'Nair',
    email: 'priya.nair@ledgerworks.io',
    phone: '(212) 884-7301',
    bio: 'Coordinates merchant onboarding, KYC exception review, and high-value account escalations for a regulated payments platform serving marketplace customers.',
    location: 'New York, NY',
    occupation: 'Payments Operations Manager',
  },
  {
    id: 3,
    firstName: 'Mateo',
    lastName: 'Johnson',
    email: 'mateo.johnson@atlasgrid.energy',
    phone: '(512) 449-2018',
    bio: 'Maintains outage communication workflows, field dispatch views, and executive reliability summaries for distributed energy infrastructure teams.',
    location: 'Austin, TX',
    occupation: 'Grid Reliability Analyst',
  },
  {
    id: 4,
    firstName: 'Elena',
    lastName: 'Williams',
    email: 'elena.williams@harborfreightlogistics.com',
    phone: '(206) 730-9188',
    bio: 'Leads shipment exception triage across ocean freight, customs holds, and warehouse appointment queues with daily SLA reporting to enterprise shippers.',
    location: 'Seattle, WA',
    occupation: 'Logistics Program Director',
  },
  {
    id: 5,
    firstName: 'Noah',
    lastName: 'Brown',
    email: 'noah.brown@civiccloud.gov',
    phone: '(312) 507-4410',
    bio: 'Runs constituent support analytics, public records routing, and secure case escalation workflows for a municipal digital services organization.',
    location: 'Chicago, IL',
    occupation: 'Civic Services Architect',
  },
];
